import Card from "components/Card";
import { Layout } from "components/layout";
import Head from "next/head";
import React from "react";

type IAskPage = {};

const AskPage = ({}: IAskPage) => {
  return (
    <Layout title="جزئیات سوال">
      <Head>
        <title>مشاهده سوال | کارنامه</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card
        id={2}
        title="title"
        body="test"
        date="2022-04-21 23:00:11"
        avatar="https://picsum.photos/32"
        type="withoutActions"
        props={{
          commentsCount: 10,
        }}
      />
      <h3 className="mt-6 font-bold">پاسخ‌ها</h3>
      <Card
        id={2}
        title="title"
        body="test"
        date="2022-04-21 23:00:11"
        avatar="https://picsum.photos/32"
        type="answer"
        props={{
          like: 20,
          dislike: 10,
        }}
      />
      <div>
        <h3 className="mt-6 text-2xl font-bold">پاسخ خود را ثبت کنید</h3>
        <form className="mt-4">
          <label htmlFor="question" className="mt-4 text-xs font-bold">
            پاسخ خود را بنویسید
          </label>
          <textarea
            id="question"
            className="form-control textarea w-full"
            placeholder="متن پرسش خود را وارد کنید"
          />
          <span className="text-[10px] text-red-400">محل قرارگیری خطا</span>
          <div className="mt-6">
            <button className="btn btnGreen h-9 w-[200px]">ارسال پاسخ</button>
          </div>
        </form>
      </div>
    </Layout>
  );
};

export default AskPage;
