import React from "react";
import Card from "components/Card";
import { Layout } from "components/layout";
import Head from "next/head";
import list from "db/database.json";

export default function Home() {
  return (
    <Layout title="لیست سوالات">
      <Head>
        <title>خرید و فروش مطمئن خودروی کارکرده | کارنامه</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {list.problems.map(({ title, body, date, id, user, solutions }) => (
        <Card
          key={id}
          id={id}
          title={title}
          body={body}
          date={date}
          avatar={user.avatar}
          type="question"
          props={{
            commentsCount: solutions.length,
          }}
        />
      ))}
    </Layout>
  );
}
