import React from "react";
import Ask from "components/Ask";
import { Header } from "components/layout";
import Head from "next/head";
import list from "db/database.json";
import Modal from "components/Modal";

export default function Home() {
  const [isOpen, setIsOpen] = React.useState(true);
  const handleToggle = () => setIsOpen((prev) => !prev);

  return (
    <>
      <Head>
        <title>خرید و فروش مطمئن خودروی کارکرده | کارنامه</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Modal isOpen={isOpen} onClose={handleToggle} />
        <Header handleCreateAsk={handleToggle} />
        <section className="container mt-3">
          {list.problems.map(({ title, body, date, id, user, solutions }) => (
            <Ask
              key={id}
              id={id}
              title={title}
              body={body}
              date={date}
              avatar={user.avatar}
              commentsCount={solutions.length}
            />
          ))}
        </section>
      </main>
    </>
  );
}
